### ISSUE TITLE
There was an error while trying to load the gem 't_t'. (Bundler::GemRequireError)

### ISSUE THREAD

**Issue by Svashtar** [jalkoby/tt#1]
Hi,

i would really like to get hands on your gem which looks quite useful, but can't load it somehow.
I am getting a mentioned error. This is a bit more:

> There was an error while trying to load the gem 't_t'. (Bundler::GemRequireError)
>   /home/XXX/.rvm/gems/ruby-2.2.2@informator/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require'
>   /home/XXX/.rvm/gems/ruby-2.2.2@informator/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in`block (2 levels) in require'
>   /home/XXX/.rvm/gems/ruby-2.2.2@informator/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
>   /home/XXX/.rvm/gems/ruby-2.2.2@informator/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in`block in require'
>   /home/XXX/.rvm/gems/ruby-2.2.2@informator/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
>   /home/XXX/.rvm/gems/ruby-2.2.2@informator/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in`require'
>   /home/XXX/.rvm/gems/ruby-2.2.2@informator/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
>   /home/XXX/projects/development/informator/config/application.rb:7:in`<top (required)>'
>   /home/XXX/projects/development/informator/config/environment.rb:2:in `require'
>   /home/XXX/projects/development/informator/config/environment.rb:2:in`<top (required)>'
>   config.ru:3:in `require'
>   config.ru:3:in`block in <main>'
>   /home/XXX/.rvm/gems/ruby-2.2.2@informator/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
>   /home/XXX/.rvm/gems/ruby-2.2.2@informator/gems/rack-1.6.4/lib/rack/builder.rb:55:in`initialize'
>   config.ru:1:in `new'
>   config.ru:1:in`<main>'
>   /home/XXX/.rvm/gems/ruby-2.1.2/gems/passenger-5.0.10/helper-scripts/rack-preloader.rb:107:in `eval'
>   /home/XXX/.rvm/gems/ruby-2.1.2/gems/passenger-5.0.10/helper-scripts/rack-preloader.rb:107:in`preload_app'
>   /home/XXX/.rvm/gems/ruby-2.1.2/gems/passenger-5.0.10/helper-scripts/rack-preloader.rb:153:in `<module:App>'
>   /home/XXX/.rvm/gems/ruby-2.1.2/gems/passenger-5.0.10/helper-scripts/rack-preloader.rb:29:in`module:PhusionPassenger'
>   /home/XXX/.rvm/gems/ruby-2.1.2/gems/passenger-5.0.10/helper-scripts/rack-preloader.rb:28:in `<main>'

**Comment by jalkoby** [comment]
It looks like you didn't run bundle before restarting the passenger

**Comment by Svashtar** [comment]
I did it several times actually, also tried moving gem up and down the Gemfile (maybe some loading order issue), but no luck. It just doesn't load with this gem.

**Comment by jalkoby** [comment]
Yes, there was a bug related to activerecord integration. Version `1.0.1` fixes it
