### ISSUE TITLE
undefined method `helper_method' for ActionController::API

### ISSUE THREAD

**Issue by Svashtar** [jalkoby/tt#4]
Hi,

i am in process of upgrading Rails from 5.0.2 to 5.1 (currently on 5.0.3), but i am having problems with t_t as described in the title. Actually, I also upgraded Draper from 3.0.0-pre1 to 3.0.0.

If i leave Draper on pre-release, then everything is fine, if i go to stable release, t_t breaks.

Error:
`.../gems/t_t-1.2.1/lib/t_t/rails.rb:20:in 'block in <module:Helper>': undefined method 'helper_method' for ActionController::API:Class (NoMethodError)`

Is there any chance you could fix this? Thx

**Comment by jalkoby** [comment]
Hi. Sure - I'll fix it ASAP. Support of rails 5.1 is a key priority

**Comment by jalkoby** [comment]
check out v1.2.2

**Comment by Svashtar** [comment]
Perfect. Works flawlessly 👍
